services:

  db:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
